### ISSUE TITLE
ConfirmSubscriberMail is queued in the default queue not in 'send-mail' queue

### ISSUE THREAD

**Issue by RicardoRamirezR** [spatie/mailcoach-support#115]
Hi there,

When sending a Confirm mail it goes to `default` queue instead of `send-mail` queue.

Adding these code
![Captura de Pantalla 2020-03-23 a la(s) 10 24 57 a  m](https://user-images.githubusercontent.com/6526545/77333082-eb120900-6cf0-11ea-8e4b-5d75f44b66ba.png)
sets the correct queue

**Comment by RicardoRamirezR** [comment]
Same for Welcome mail

![Captura de Pantalla 2020-03-23 a la(s) 10 52 59 a  m](https://user-images.githubusercontent.com/6526545/77335691-8193f980-6cf4-11ea-836b-22c0e123c04d.png)

So, I think there is an issue from my side

**Comment by freekmurze** [comment]
The `send-mail` queue is only meant for campaign mails. I'll rename it in a next major release. Using it to send transactional mails might not be the best idea because when sending a campaign, that queue will contain a lot of jobs, and transactional mails may go out with a long delay.

I think the way to go now if you want to put to confirmation mail on another queue, would be to customise the `SendConfirmSubscriberMailAction` and put the mail sent there on a queue of your liking.

We'll improve on this in the next major version.
