### ISSUE TITLE
[Feature] custom placeholder per emaillist

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#141]
Very often you have the case that you want to use your address, imprint, social links, just an image or some textblocks in your template and don't repalce it in every template when something changes..

Custom Placeholders per emailList should be the solution for this.

Huge patch for this (compatible with 2.4.6):
[custom_placeholder_per_emaillist.patch.zip](https://github.com/spatie/mailcoach-support/files/4429985/custom_placeholder_per_emaillist.patch.zip)

Updates:
0.1 initial commit custom placeholder
0.2 added rules for naming placeholders

![Screenshot 2020-04-03 23 26 34](https://user-images.githubusercontent.com/4960172/78406277-9af54980-7602-11ea-9578-4ba421b87c3f.png)

**Comment by freekmurze** [comment]
Thanks for your work on this.

We'll discuss this internally whether we want to add this.

**Comment by freekmurze** [comment]
We've decided not to add this, because we suspect not many users will need this and we'd like to keep Mailcoach as simple as it can be.

In Mailcoach v2.6 I've added and empty view `mailcoach::app.emailLists.layouts.partials.afterLastTab`. You can publish this view to add extra tabs in your own project.

**Comment by timmoh** [comment]
I've published a package out of this: https://github.com/timmoh/mailcoach-custom-placeholder
So everybody is able to use it as an add-on.
to keep it compatible: `mailcoach::app.emailLists.layouts.partials.afterLastTab` has to be set up by everyone on his own

**Comment by jmichaelterenin** [comment]
I haven't taken a look yet at the package, but I can quickly/safely say that this is something my client very much **assumes** would be available in the MailCoach package. Thanks for your work @timmoh. It's very possible that I will want to add on so that model / database fields can be utilized here as well.

**Comment by Vardkin** [comment]
> I haven't taken a look yet at the package, but I can quickly/safely say that this is something my client very much **assumes** would be available in the MailCoach package. Thanks for your work @timmoh. It's very possible that I will want to add on so that model / database fields can be utilized here as well.

I have to second this. I just deployed Mailcoach for my marketing team yesterday (2020-09-28) and the first thing they responded to me with was, "I can't add custom fields?"

I'll be installing your addon @timmoh. Thank you for sharing your work.

**Comment by timmoh** [comment]
@Vardkin feel free to add some additional fields via pr.
I think @freekmurze has already said that it want go into mailcoach... but i think with this open source repo/addon everybody can expand the placeholder...
