### ISSUE TITLE
[Suggestion] Change Scheduled to triggered campaign 

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#143]
My suggestion on recurring campaigns (#130) was not approved. So I've thought a little bit about it:

Perhaps it's possible to change the scheduled campaigns to triggered campaigns. Then everybody is possible to write his own triggers and it's more flexible for add-ons

The triggers can be:
- Scheduled time (like actually implemented)
- any laravel event/action
- other campaigns
- webhook
- artisan command
- ...

**Comment by freekmurze** [comment]
If you know your way around Laravel, you can already programmatically send campaigns using all of these triggers.

Take a look in the creating a campaign section of the docs to learn more
https://mailcoach.app/docs/v2/package/working-with-campaigns/creating-a-campaign

We currently won't provide a UI for this because we want to keep the UI very simple.
