### ISSUE TITLE
[Suggestion] Track links clicks... by mailcoach directly

### ISSUE THREAD

**Issue by timmoh** [spatie/mailcoach-support#152]
Wouldn't it be a more secure way to track the links in the campaign emails directly by mailcoach and not by any other provider (ses, mailgun etc.)

Just Replace the links in the emails with any link like: mailcoach.app/redirect/234234-34-234-23423-4323 -> via 301 -> orginal link

**Comment by freekmurze** [comment]
I've done that in a first version of Mailcoach, but I moved away from that approach. The problem here is that you can very easily ddos yourself when sending out campaigns. All opens and clicks will result in an extra request to your app. 

Most of the email providers throttles this kind of feedback, and have the ability to resend feedback, if your server was unable to handle the feedback.

If you're interested in the code, take a look at the first commits on the laravel-mailcoach repo (you can request access now via your account on https://mailcoach.app).
