### ISSUE TITLE
[Feature Request] Paste Campaign Recipients

### ISSUE THREAD

**Issue by gustavo-2830** [spatie/mailcoach-support#165]
I would like to be able to paste a comma-separated list of emails as a list of recipients for any campaign. Similar to how tests are sent but making sure the email is subscribed to the list. Right now If I need to send to a very specific list I need to either create a new list with these subscribers or create a tag. None of these options are desired as this specific list is most likely to be used once.

**Comment by freekmurze** [comment]
We probably will not add this because we'd like to keep Mailcoach simple and think not too many users need this feature.

For now, create a list. You could automate it a bit by creating an artisan command that accepts a string of comma separated emailaddresses. In the command create a new list and add the email addresses as subscribers.
