### ISSUE TITLE
FR: Import/migrate from Sendy

### ISSUE THREAD

**Issue by lesaff** [spatie/mailcoach-support#182]
@freekmurze first of, congrats with Mailcoach. It's about time that Sendy has a competition.
We've been using Sendy for a few years now. I would love to use Mailcoach but the thought of moving brands over to Mailcoach manually would deter my effort.

It would be super if there is an easy way for existing Sendy users to migrate to Mailcoach.

What do you think?

**Comment by freekmurze** [comment]
Thanks for your kind words and your suggestion. I'd like to keep the core of Mailcoach as simple (and maintainable) as it can be. That's why I probably won't include some kind of migration code.

Feel free to develop a migration from Sendy yourself and optionally share and document the code on GitHub. I'd be more than happy to share a link to such a migration in our docs.
