### ISSUE TITLE
Options to choose beween comma and semicolon separator when importing .csv

### ISSUE THREAD

**Issue by rjnicolai** [spatie/mailcoach-support#195]
Excel exports .csv with a semicolon as separator on default. Mailcoach requires the separator to be a comma.  We'd love the option to change the separator in Mailcoach, to make importing more smoothly and simple to understand for our users

**Comment by freekmurze** [comment]
That makes sense, thanks for your suggestion. We'll take care of making the delimiter configurable soon.

**Comment by riasvdv** [comment]
This is something you can customize yourself by replacing the `mailcoach.actions.import_subscribers` action with a class of your own that extends our `\Spatie\Mailcoach\Actions\Subscribers\ImportSubscribersAction::class` and overwriting the `importSubscribers()` method (you can basically copy-paste the method and add the `useDelimiter` option to the SimpleExcelReader)

Implementing this now would require a breaking change in the package as the signature of the class would change. Hope you can solve it this way.

**Comment by mbardelmeijer** [comment]
This something that can be visited for Mailcoach V3? We notice clients have issues with importing CSV files due to system settings with delimiter. Would love to see native Excel import support for instance (we normally use https://github.com/Maatwebsite/Laravel-Excel for that).

Can PR something into `spatie/laravel-mailcoach` if wanted?

**Comment by freekmurze** [comment]
@mbardelmeijer Feel free to submit a PR to v3. We aim to release v3 somewhere next week.
