### ISSUE TITLE
Customization of Frontend 

### ISSUE THREAD

**Issue by bluelupin** [spatie/mailcoach-support#203]
This issue is continuation to the closed issue - https://github.com/spatie/mailcoach-support/issues/180

I was able to customize the frontend as per the instructions. However, following are a few observations:

1. **[Critical]** Though landingPages directory is also copied in the vendor folder, changes are not reflected.
2. It would be great if we could specify the vendor folder name ourselves
3. The CSS file is copied in the vendor folder in compiled (minified) form. Are there any instructions to edit CSS.

**Comment by freekmurze** [comment]
1. Maybe you've cached your views? Run `php artisan views:clear`

2. I assume you mean the `vendor` directory in the `resources/views` directory. We can't change that. This name is hardcoded in Laravel.

3. Maybe @sebastiandedeyne can answer that one.

**Comment by sebastiandedeyne** [comment]
Hi @bluelupin!

Since Mailcoach uses [Tailwind](https://tailwindcss.com), we generally recommend updating views instead of globally modifying CSS. We might make Mailcoach more "themeable" in the future, but that's not on the roadmap right now.

You can always register additional CSS by pushing it to the `endHead` stack from your views.

```blade
@push('endHead')
    <link rel="stylesheet" href="{{ mix('my-stylesheet.css') }}">
@endpush
```

See https://github.com/spatie/laravel-mailcoach/blob/c5572886fecaef69087d75952779e41b7ea0fe06/resources/views/app/layouts/app.blade.php#L19
