### ISSUE TITLE
allow mail driver configuration secrets to be set in config file rather than stored in database

### ISSUE THREAD

**Issue by vesper8** [spatie/mailcoach-support#22]
There is something bothering me about #1 having to duplicate the key values for my mailgun configuration in both the .env file and having to enter them manually in the UI for them to be stored (I assume, didn't check) in a database table, and #2 for having to store these keys in a database table at all.

I would much rather these secrets be defined in one only place, the .env file, and then defined in the mailcoach.php configuration file, similar to how the /config/services.php file is structured

This would allow me to easily switch between two providers without having to re-enter the secrets in the UI. And I would feel safer knowing all my secrets are in one place, the usual place.

**Comment by freekmurze** [comment]
If you use the Mailcoach stand alone app, that it is assumed that you don't want to configure your Laravel app yourself. That's why we added UI to specify those values. If you specify them in the UI, we save them in the UI and you don't need to specify them somewhere else.

If you want to work with these values like in a normal Laravel app, namely store them in the `.env` file, then I highly recommend using mailcoach as a package inside a Laravel app of your own. When installed this way, there simply isn't any UI to set these configuration values.

If you want to use multiple email service providers in one app, I suggest waiting a bit until we update Mailcoach for Laravel 7, which will allow for having defined multiple email service providers in one app.

Closing this for now, because I don't think we will make any adjustments, but if you have more question or remarks on this, feel free to keep the conversation going here.
