### ISSUE TITLE
Customised confirmation email column has the wrong data type

### ISSUE THREAD

**Issue by jorenvh** [spatie/mailcoach-support#68]
For my list I'm willing to send a customised confirmation email, this feature is available through the UI as you know. However the database field representing the field is a `varchar(255)` which prevents me from adding a html template to it.

Changing the `data_type` to `text` resolves the issue.

```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'confirmation_mail_content'
```

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. I've updated the default migration.

**Comment by jorenvh** [comment]
No problem, It might also be a good idea to add a new migration that changes the data type for the column. This way existing applications get updated when they pull in the latest version.

What do you think?

**Comment by freekmurze** [comment]
I don't think that auto updating the database after a package update is a good idea. People who already installed the package and hit this problem, can manually update their database scheme.

**Comment by ryancwalsh** [comment]
One thought, though, is that it might be best if it were possible for people who have already installed the package to have some sort of official way of knowing when there are manual fixes required (so that they can prevent the problem). 

It would be unfortunate to need to first experience a bug / undesirable situation and then search the issues site and realize that someone already knew about the problem and that it could have been avoided.

**Comment by jorenvh** [comment]
@freekmurze fair enough!
